In [ ]:
## Metodos responsaveis pelo pre processamento

# Com Outliers  Com Normalização Sem Unamed


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds = df_diamonds.drop(df_diamonds.columns[[0]], axis=1)
df_number_type = df_diamonds.select_dtypes(exclude='O')

df_diamonds[df_diamonds.duplicated()].info()

y=df_number_type['price']
X=df_number_type.drop('price', axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix

sc=StandardScaler()
X_train_tx=sc.fit_transform(X_train)
X_test_tx=sc.transform(X_test)

dataset_1=(X_train, X_test, y_train, y_test, 'dataset_1')

model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]


def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(n_jobs=-1, estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)


model_dict={'LinearRegression': LinearRegression(),
           'RandomForestRegressor': RandomForestRegressor(), 
           'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)

           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])

accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 1005 to 52861
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    146 non-null    float64
 1   cut      146 non-null    object 
 2   color    146 non-null    object 
 3   clarity  146 non-null    object 
 4   depth    146 non-null    float64
 5   table    146 non-null    float64
 6   price    146 non-null    int64  
 7   x        146 non-null    float64
 8   y        146 non-null    float64
 9   z        146 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 12.5+ KB


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.1s finished



#### LinearRegression ####
score :0.8603
[0.85929859 0.8546376  0.86308003 0.85616085 0.85896936]

MSE    : 2171054.35 
MAE    : 894.87 
RMSE   : 1473.45 
R2     : 0.86 


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:691: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:   53.5s finished



#### RandomForestRegressor ####
score :0.8805
[0.87318664 0.8786663  0.88398218 0.8737674  0.87813642]

MSE    : 1857131.04 
MAE    : 783.80 
RMSE   : 1362.77 
R2     : 0.88 


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.7s finished



#### KNeighborsRegressor ####
score :0.8666
[0.86201044 0.86328527 0.86735416 0.86217312 0.86233278]

MSE    : 2072497.17 
MAE    : 821.10 
RMSE   : 1439.62 
R2     : 0.87 
Iteration 1, loss = 1703431.03922542
Iteration 2, loss = 1196819.33054975
Iteration 3, loss = 1195348.85966304
Iteration 4, loss = 1182228.01488569
Iteration 5, loss = 1165707.55978305
Iteration 6, loss = 1161874.46641999
Iteration 7, loss = 1142836.50931182
Iteration 8, loss = 1123335.43861061
Iteration 9, loss = 1098933.74375387
Iteration 10, loss = 1078793.54564813
Iteration 11, loss = 1068946.10257604
Iteration 12, loss = 1060992.93250390
Iteration 13, loss = 1055270.80084534
Iteration 14, loss = 1057064.64507844
Iteration 15, loss = 1062171.34976387
Iteration 16, loss = 1052266.47867615
Iteration 17, loss = 1047215.39148200
Iteration 18, loss = 1052628.68497232
Iteration 19, loss = 1049503.50577366
Iteration 20, loss = 1048195.94993412
Iteration 21, loss = 1046628.11082287
Iteration 22, loss = 1043570.29053100

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.



#### MLPRegressor ####
score :0.8667
[0.87120285 0.87235221 0.87954498 0.86523996 0.8688524 ]

MSE    : 2071728.35 
MAE    : 811.80 
RMSE   : 1439.35 
R2     : 0.87 


[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 17.2min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.860279  ...              1473.449812  0.860279
1  RandomForestRegressor       0.880482  ...              1362.765953  0.880482
2    KNeighborsRegressor       0.866622  ...              1439.617022  0.866622
3           MLPRegressor       0.866671  ...              1439.349976  0.866671

[4 rows x 7 columns]

# Com Outliers  Com Normalização com *unamed*


In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds[df_diamonds.duplicated()].info()
df_number_type = df_diamonds.select_dtypes(exclude='O')


y=df_number_type['price']
X=df_number_type.drop('price', axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPRegressor


sc=StandardScaler()
X_train_tx=sc.fit_transform(X_train)
X_test_tx=sc.transform(X_test)

dataset_1=(X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]


def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(n_jobs=-1, estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)


model_dict={'LinearRegression': LinearRegression(),
           'RandomForestRegressor': RandomForestRegressor(), 
           'KNeighborsRegressor': KNeighborsRegressor(),
           'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)
           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])

accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      int64  
 1   carat       0 non-null      float64
 2   cut         0 non-null      object 
 3   color       0 non-null      object 
 4   clarity     0 non-null      object 
 5   depth       0 non-null      float64
 6   table       0 non-null      float64
 7   price       0 non-null      int64  
 8   x           0 non-null      float64
 9   y           0 non-null      float64
 10  z           0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 0.0+ bytes


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    1.3s finished



#### LinearRegression ####
score :0.8611
[0.8601141  0.85515871 0.86385021 0.85686318 0.85983774]

MSE    : 2158838.67 
MAE    : 905.55 
RMSE   : 1469.30 
R2     : 0.86 


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:   59.3s finished



#### RandomForestRegressor ####
score :0.9999
[0.99985466 0.99982998 0.9998968  0.99981602 0.99989272]

MSE    : 1565.70 
MAE    : 5.66 
RMSE   : 39.57 
R2     : 1.00 


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.6s finished



#### KNeighborsRegressor ####
score :0.9935
[0.99312903 0.99454886 0.99431777 0.99525537 0.99247625]

MSE    : 101363.53 
MAE    : 34.67 
RMSE   : 318.38 
R2     : 0.99 
Iteration 1, loss = 5717251.49619160
Iteration 2, loss = 3583539.73940808
Iteration 3, loss = 2111735.28782188
Iteration 4, loss = 1497535.91803554
Iteration 5, loss = 1305675.65054641
Iteration 6, loss = 1201616.36543659
Iteration 7, loss = 1151017.42938439
Iteration 8, loss = 1083416.94304019
Iteration 9, loss = 1056419.13939117
Iteration 10, loss = 1059493.73382037
Iteration 11, loss = 985309.32688432
Iteration 12, loss = 956402.82447833
Iteration 13, loss = 944771.60399517
Iteration 14, loss = 931743.35224766
Iteration 15, loss = 929797.90310595
Iteration 16, loss = 904190.06771975
Iteration 17, loss = 885858.53133951
Iteration 18, loss = 870363.41384105
Iteration 19, loss = 885656.46774221
Iteration 20, loss = 875109.15440402
Iteration 21, loss = 864968.46605057
Iteration 22, loss = 864017.61835826
Iteration 23, 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.



#### MLPRegressor ####
score :0.9367
[0.93478928 0.92131464 0.83109559 0.91679391 0.93216548]

MSE    : 982947.51 
MAE    : 698.70 
RMSE   : 991.44 
R2     : 0.94 


[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 17.4min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.861065  ...              1469.298701  0.861065
1  RandomForestRegressor       0.999899  ...                39.568878  0.999899
2    KNeighborsRegressor       0.993477  ...               318.376394  0.993477
3           MLPRegressor       0.936741  ...               991.437093  0.936741

[4 rows x 7 columns]

# Com outliers sem normalizacao sem Unamed

In [1]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds = df_diamonds.drop(df_diamonds.columns[[0]], axis=1)

df_diamonds[df_diamonds.duplicated()].info()
df_number_type = df_diamonds.select_dtypes(exclude='O')


y=df_number_type['price']
X=df_number_type.drop('price', axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPRegressor


# sc=StandardScaler()
# X_train_tx=sc.fit_transform(X_train)
# X_test_tx=sc.transform(X_test)

dataset_1=(X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]


def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(n_jobs=-1, estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)


model_dict={'LinearRegression': LinearRegression(),
           'RandomForestRegressor': RandomForestRegressor(), 
           'KNeighborsRegressor': KNeighborsRegressor(),
           'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)
           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])

accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 1005 to 52861
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    146 non-null    float64
 1   cut      146 non-null    object 
 2   color    146 non-null    object 
 3   clarity  146 non-null    object 
 4   depth    146 non-null    float64
 5   table    146 non-null    float64
 6   price    146 non-null    int64  
 7   x        146 non-null    float64
 8   y        146 non-null    float64
 9   z        146 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 12.5+ KB


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    5.8s finished



#### LinearRegression ####
score :0.8603
[0.85929859 0.8546376  0.86308003 0.85616085 0.85896936]

MSE    : 2171054.35 
MAE    : 894.87 
RMSE   : 1473.45 
R2     : 0.86 


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


KeyboardInterrupt: 

# Sem Outliers  Com Normalização com *unamed*

In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds[df_diamonds.duplicated()].info()

df_number_type = df_diamonds.select_dtypes(exclude='O').columns[1:]

def range_for_remove_outliers(attr):
    df_attr = df_diamonds[attr]
    q3 = df_attr.quantile(q=0.75)
    q1 = df_attr.quantile(q=0.25)

    IQR  = q3 - q1
    min_IQR = q1 - 1.5 * IQR
    max_IQR = q3 + 1.5 * IQR
    
    return (min_IQR,max_IQR)

def remove_outlier(df_in, col_name):
    range_iqr = range_for_remove_outliers(col_name)
    df_out = df_in[~((df_in < range_iqr[0]) |(df_in > range_iqr[1])).any(axis=1)]
    return df_out


import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds_ro = remove_outlier(df_diamonds.select_dtypes(exclude='O'),df_number_type)

y=df_diamonds_ro['price']
X=df_diamonds_ro.drop('price', axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix

sc=StandardScaler()
X_train_tx=sc.fit_transform(X_train)
X_test_tx=sc.transform(X_test)

dataset_1=(X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]


def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)


model_dict={'LinearRegression': LinearRegression(),
           'RandomForestRegressor': RandomForestRegressor(), 
            'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)
           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])

accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      int64  
 1   carat       0 non-null      float64
 2   cut         0 non-null      object 
 3   color       0 non-null      object 
 4   clarity     0 non-null      object 
 5   depth       0 non-null      float64
 6   table       0 non-null      float64
 7   price       0 non-null      int64  
 8   x           0 non-null      float64
 9   y           0 non-null      float64
 10  z           0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 0.0+ bytes


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished



#### LinearRegression ####
score :0.8611
[0.8508012  0.86313829 0.86698611 0.86094914 0.86214544]

MSE    : 1016587.99 
MAE    : 627.90 
RMSE   : 1008.26 
R2     : 0.86 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.2min finished



#### RandomForestRegressor ####
score :0.9998
[0.99969099 0.99963411 0.99971844 0.99975671 0.9998425 ]

MSE    : 1438.55 
MAE    : 6.74 
RMSE   : 37.93 
R2     : 1.00 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.5s finished



#### KNeighborsRegressor ####
score :0.9947
[0.98901651 0.99019119 0.98773833 0.99005624 0.98970058]

MSE    : 38835.63 
MAE    : 25.94 
RMSE   : 197.07 
R2     : 0.99 
Iteration 1, loss = 2679462.66773641
Iteration 2, loss = 1276130.23038648
Iteration 3, loss = 775289.43802786
Iteration 4, loss = 691287.36507850
Iteration 5, loss = 626101.17130588
Iteration 6, loss = 546915.20265066
Iteration 7, loss = 499588.66282900
Iteration 8, loss = 456675.01124959
Iteration 9, loss = 448772.73967857
Iteration 10, loss = 447288.16231059
Iteration 11, loss = 428611.01992367
Iteration 12, loss = 422053.35116102
Iteration 13, loss = 404230.42599598
Iteration 14, loss = 393902.14717621
Iteration 15, loss = 382681.16022808
Iteration 16, loss = 380119.85438786
Iteration 17, loss = 374387.64516109
Iteration 18, loss = 372968.48243640
Iteration 19, loss = 368921.36554043
Iteration 20, loss = 362940.66534379
Iteration 21, loss = 366229.95793564
Iteration 22, loss = 347278.70250470
Iteration 23, loss = 35

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Iteration 1, loss = 2764690.39680945
Iteration 2, loss = 2046297.04023148
Iteration 3, loss = 1692928.50738722
Iteration 4, loss = 1244063.06248989
Iteration 5, loss = 852581.70627977
Iteration 6, loss = 641202.06898953
Iteration 7, loss = 593242.83149883
Iteration 8, loss = 603614.61885958
Iteration 9, loss = 569770.09200662
Iteration 10, loss = 535581.94987159
Iteration 11, loss = 531676.20726236
Iteration 12, loss = 528286.52729796
Iteration 13, loss = 486553.25823289
Iteration 14, loss = 489407.62640604
Iteration 15, loss = 482799.69461532
Iteration 16, loss = 462671.84777214
Iteration 17, loss = 455608.87393547
Iteration 18, loss = 458724.73531344
Iteration 19, loss = 449346.90296652
Iteration 20, loss = 447290.51928920
Iteration 21, loss = 423331.49840538
Iteration 22, loss = 439127.73730325
Iteration 23, loss = 429352.61086076
Iteration 24, loss = 423021.45455178
Iteration 25, loss = 440709.03477050
Iteration 26, loss = 413953.59849584
Iteration 27, loss = 420818.45970292
Iterat

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 2365722.95080141
Iteration 2, loss = 1277285.65578748
Iteration 3, loss = 915156.18690404
Iteration 4, loss = 805985.11742538
Iteration 5, loss = 708661.28597939
Iteration 6, loss = 622725.33790311
Iteration 7, loss = 578549.29853450
Iteration 8, loss = 521814.31608494
Iteration 9, loss = 494176.88696271
Iteration 10, loss = 511092.84551580
Iteration 11, loss = 478886.08504048
Iteration 12, loss = 458690.44822175
Iteration 13, loss = 457855.05629777
Iteration 14, loss = 440692.16664134
Iteration 15, loss = 416046.98981261
Iteration 16, loss = 418442.60377386
Iteration 17, loss = 395828.14626671
Iteration 18, loss = 408678.27037704
Iteration 19, loss = 403692.31738661
Iteration 20, loss = 394607.30589497
Iteration 21, loss = 382020.61899858
Iteration 22, loss = 372295.03294968
Iteration 23, loss = 368531.80186983
Iteration 24, loss = 371083.35433834
Iteration 25, loss = 359480.87244436
Iteration 26, loss = 359629.77213847
Iteration 27, loss = 354170.92404774
Iteratio

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 2757072.53876207
Iteration 2, loss = 1324547.60226858
Iteration 3, loss = 899207.17775157
Iteration 4, loss = 735944.65142949
Iteration 5, loss = 633565.26386923
Iteration 6, loss = 607146.48217597
Iteration 7, loss = 544841.15280384
Iteration 8, loss = 525287.71868075
Iteration 9, loss = 487305.86651180
Iteration 10, loss = 490767.32777988
Iteration 11, loss = 470490.47397335
Iteration 12, loss = 448303.07911560
Iteration 13, loss = 451265.45936140
Iteration 14, loss = 441047.78164643
Iteration 15, loss = 413971.48323471
Iteration 16, loss = 416713.98254289
Iteration 17, loss = 392973.45623691
Iteration 18, loss = 395664.32277656
Iteration 19, loss = 398560.09652926
Iteration 20, loss = 377033.38187154
Iteration 21, loss = 375975.91094687
Iteration 22, loss = 377821.71028412
Iteration 23, loss = 358029.96904127
Iteration 24, loss = 362020.56656914
Iteration 25, loss = 361579.82532970
Iteration 26, loss = 356604.89936950
Iteration 27, loss = 348073.83204723
Iteratio

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 2646011.56094805
Iteration 2, loss = 1259746.52254208
Iteration 3, loss = 901329.84970594
Iteration 4, loss = 769510.29253113
Iteration 5, loss = 687899.12195724
Iteration 6, loss = 622904.83441394
Iteration 7, loss = 570071.61705797
Iteration 8, loss = 616208.84600082
Iteration 9, loss = 559603.54594000
Iteration 10, loss = 519152.98366081
Iteration 11, loss = 505001.21676670
Iteration 12, loss = 471994.39169112
Iteration 13, loss = 471081.30101465
Iteration 14, loss = 469501.89239362
Iteration 15, loss = 442306.78116336
Iteration 16, loss = 446817.70600731
Iteration 17, loss = 418747.82135159
Iteration 18, loss = 417975.77518454
Iteration 19, loss = 409400.91655888
Iteration 20, loss = 399986.45513121
Iteration 21, loss = 388260.20240907
Iteration 22, loss = 385429.72615743
Iteration 23, loss = 383502.83085110
Iteration 24, loss = 378151.51897415
Iteration 25, loss = 368706.11360155
Iteration 26, loss = 361540.46050870
Iteration 27, loss = 367112.68958237
Iteratio

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 2795045.14989763
Iteration 2, loss = 1287506.66954523
Iteration 3, loss = 945980.92470627
Iteration 4, loss = 787469.81880063
Iteration 5, loss = 692262.29599553
Iteration 6, loss = 601323.55753278
Iteration 7, loss = 608262.06170372
Iteration 8, loss = 562719.74175480
Iteration 9, loss = 531801.86503177
Iteration 10, loss = 512025.99907903
Iteration 11, loss = 494905.49736711
Iteration 12, loss = 477408.07990463
Iteration 13, loss = 451633.93057265
Iteration 14, loss = 443488.84421012
Iteration 15, loss = 424903.86771247
Iteration 16, loss = 433315.52901173
Iteration 17, loss = 415830.73492386
Iteration 18, loss = 408115.71625478
Iteration 19, loss = 402065.61085169
Iteration 20, loss = 398297.05088466
Iteration 21, loss = 394816.36036444
Iteration 22, loss = 382884.75548615
Iteration 23, loss = 378762.99220432
Iteration 24, loss = 374418.51824056
Iteration 25, loss = 369326.65507802
Iteration 26, loss = 355080.26879643
Iteration 27, loss = 356063.60007063
Iteratio

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 19.0min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.861113  ...              1008.259885  0.861113
1  RandomForestRegressor       0.999803  ...                37.928255  0.999803
2    KNeighborsRegressor       0.994694  ...               197.067574  0.994694
3           MLPRegressor       0.945011  ...               634.421764  0.945011

[4 rows x 7 columns]

# Sem Outiliers Sem Normalizacao com unamed


In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds[df_diamonds.duplicated()].info()

df_number_type = df_diamonds.select_dtypes(exclude='O').columns[1:]


def range_for_remove_outliers(attr):
    df_attr = df_diamonds[attr]
    q3 = df_attr.quantile(q=0.75)
    q1 = df_attr.quantile(q=0.25)

    IQR  = q3 - q1
    min_IQR = q1 - 1.5 * IQR
    max_IQR = q3 + 1.5 * IQR
    
    return (min_IQR,max_IQR)

def remove_outlier(df_in, col_name):
    range_iqr = range_for_remove_outliers(col_name)
    df_out = df_in[~((df_in < range_iqr[0]) |(df_in > range_iqr[1])).any(axis=1)]
    return df_out



df_diamonds_ro = remove_outlier(df_diamonds.select_dtypes(exclude='O'),df_number_type)

y=df_diamonds_ro['price']
X=df_diamonds_ro.drop('price', axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.4, random_state=1)

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

sc=StandardScaler()
X_train_tx=sc.fit_transform(X_train)
X_test_tx=sc.transform(X_test)


dataset_1 = (X_train_tx, X_test_tx, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]

def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)

model_dict={'LinearRegression': LinearRegression(),
            'RandomForestRegressor': RandomForestRegressor(), 
            'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=4, learning_rate_init=0.01, learning_rate="adaptive", max_iter=100, verbose=True)


           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])
accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      int64  
 1   carat       0 non-null      float64
 2   cut         0 non-null      object 
 3   color       0 non-null      object 
 4   clarity     0 non-null      object 
 5   depth       0 non-null      float64
 6   table       0 non-null      float64
 7   price       0 non-null      int64  
 8   x           0 non-null      float64
 9   y           0 non-null      float64
 10  z           0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 0.0+ bytes


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished



#### LinearRegression ####
score :0.8581
[0.85858014 0.86393974 0.8667698  0.86217502 0.86096177]

MSE    : 1070377.70 
MAE    : 640.04 
RMSE   : 1034.59 
R2     : 0.86 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   54.2s finished



#### RandomForestRegressor ####
score :0.9997
[0.99959852 0.99970951 0.99966511 0.99969875 0.99983903]

MSE    : 2003.03 
MAE    : 7.78 
RMSE   : 44.76 
R2     : 1.00 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.6s finished



#### KNeighborsRegressor ####
score :0.9833
[0.98182618 0.98028807 0.98095504 0.981171   0.98146339]

MSE    : 126323.01 
MAE    : 175.56 
RMSE   : 355.42 
R2     : 0.98 
Iteration 1, loss = 582617.36229947
Iteration 2, loss = 235122.20620455
Iteration 3, loss = 121126.34033815
Iteration 4, loss = 71000.94079965
Iteration 5, loss = 49190.05782004
Iteration 6, loss = 38222.98974114
Iteration 7, loss = 32069.70406567
Iteration 8, loss = 27724.29178748
Iteration 9, loss = 24904.95614597
Iteration 10, loss = 22449.62394702
Iteration 11, loss = 20695.79495180
Iteration 12, loss = 19383.22106998
Iteration 13, loss = 18454.09385542
Iteration 14, loss = 17662.69109599
Iteration 15, loss = 16943.09710633
Iteration 16, loss = 16376.71835179
Iteration 17, loss = 15787.34305042
Iteration 18, loss = 15149.95455610
Iteration 19, loss = 14317.62872724
Iteration 20, loss = 13432.67967907
Iteration 21, loss = 12766.24016611
Iteration 22, loss = 12078.34529645
Iteration 23, loss = 11315.52756281
Iterat

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Iteration 1, loss = 606566.65173766
Iteration 2, loss = 271932.60111188
Iteration 3, loss = 183478.59974821
Iteration 4, loss = 121352.14303405
Iteration 5, loss = 76724.79270864
Iteration 6, loss = 55573.17232375
Iteration 7, loss = 44053.93911281
Iteration 8, loss = 37962.90011930
Iteration 9, loss = 33661.71534586
Iteration 10, loss = 30682.47730035
Iteration 11, loss = 27468.43302548
Iteration 12, loss = 24390.76612340
Iteration 13, loss = 22391.73821358
Iteration 14, loss = 20765.64127097
Iteration 15, loss = 19260.58903076
Iteration 16, loss = 18015.14856319
Iteration 17, loss = 16705.08827685
Iteration 18, loss = 15736.26301826
Iteration 19, loss = 14602.30184390
Iteration 20, loss = 13793.73395576
Iteration 21, loss = 13023.79800468
Iteration 22, loss = 12166.49660530
Iteration 23, loss = 11002.82744521
Iteration 24, loss = 9859.58073493
Iteration 25, loss = 9055.05636683
Iteration 26, loss = 8534.27579698
Iteration 27, loss = 8267.55726144
Iteration 28, loss = 7815.81066157
It

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 629562.68744601
Iteration 2, loss = 245022.49181065
Iteration 3, loss = 142330.96071865
Iteration 4, loss = 88975.61334203
Iteration 5, loss = 58606.49305302
Iteration 6, loss = 44605.13536009
Iteration 7, loss = 37169.98665376
Iteration 8, loss = 32308.28282087
Iteration 9, loss = 28186.55203039
Iteration 10, loss = 24950.70726440
Iteration 11, loss = 22618.99625038
Iteration 12, loss = 20890.00338627
Iteration 13, loss = 19535.69364940
Iteration 14, loss = 18295.56290518
Iteration 15, loss = 17833.64909009
Iteration 16, loss = 16898.42454883
Iteration 17, loss = 16652.03759369
Iteration 18, loss = 15977.45555313
Iteration 19, loss = 15830.55078391
Iteration 20, loss = 15353.74488930
Iteration 21, loss = 14883.27176263
Iteration 22, loss = 14647.73835369
Iteration 23, loss = 14411.16491785
Iteration 24, loss = 14246.05014964
Iteration 25, loss = 14262.71438558
Iteration 26, loss = 13926.48512575
Iteration 27, loss = 13756.90048091
Iteration 28, loss = 13583.5899459

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 635982.56631615
Iteration 2, loss = 310064.30552500
Iteration 3, loss = 210155.54189686
Iteration 4, loss = 134832.52890343
Iteration 5, loss = 92140.76744570
Iteration 6, loss = 67766.67917926
Iteration 7, loss = 52034.96123689
Iteration 8, loss = 41767.53110216
Iteration 9, loss = 35499.14773059
Iteration 10, loss = 30670.46141974
Iteration 11, loss = 27343.15876568
Iteration 12, loss = 24836.54365995
Iteration 13, loss = 22599.26177251
Iteration 14, loss = 21018.47457896
Iteration 15, loss = 19730.55465962
Iteration 16, loss = 18784.27820086
Iteration 17, loss = 17816.48115995
Iteration 18, loss = 17106.75308755
Iteration 19, loss = 16501.33751707
Iteration 20, loss = 15772.54918563
Iteration 21, loss = 15339.41289731
Iteration 22, loss = 14553.19594758
Iteration 23, loss = 13310.00710825
Iteration 24, loss = 12300.12669584
Iteration 25, loss = 11503.25089285
Iteration 26, loss = 10487.78676027
Iteration 27, loss = 9725.68336473
Iteration 28, loss = 9202.44049437

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 578985.92769625
Iteration 2, loss = 218287.75822927
Iteration 3, loss = 128658.81739208
Iteration 4, loss = 84436.88716569
Iteration 5, loss = 61648.00141677
Iteration 6, loss = 48724.14060190
Iteration 7, loss = 40811.28711252
Iteration 8, loss = 35567.78360976
Iteration 9, loss = 30822.77279201
Iteration 10, loss = 26571.80854981
Iteration 11, loss = 22871.59908029
Iteration 12, loss = 20532.78077389
Iteration 13, loss = 17572.19018621
Iteration 14, loss = 15123.40864274
Iteration 15, loss = 13493.89051190
Iteration 16, loss = 12036.94510396
Iteration 17, loss = 11283.98892786
Iteration 18, loss = 10546.46437757
Iteration 19, loss = 9743.83638925
Iteration 20, loss = 9416.01900311
Iteration 21, loss = 8955.86819087
Iteration 22, loss = 8557.03007860
Iteration 23, loss = 8489.02565496
Iteration 24, loss = 8220.49240573
Iteration 25, loss = 8035.61526610
Iteration 26, loss = 8094.01807574
Iteration 27, loss = 7849.96406487
Iteration 28, loss = 7744.17976719
Iteratio

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 628697.89010385
Iteration 2, loss = 275067.05772427
Iteration 3, loss = 164682.74801364
Iteration 4, loss = 110939.65527119
Iteration 5, loss = 78745.37246868
Iteration 6, loss = 56347.79132812
Iteration 7, loss = 43628.22923449
Iteration 8, loss = 36239.66365717
Iteration 9, loss = 31177.32998612
Iteration 10, loss = 27463.73551864
Iteration 11, loss = 24635.23306408
Iteration 12, loss = 22365.54824532
Iteration 13, loss = 20517.83389178
Iteration 14, loss = 19366.60910974
Iteration 15, loss = 18220.17365239
Iteration 16, loss = 17288.31413301
Iteration 17, loss = 16685.49805731
Iteration 18, loss = 16237.79778185
Iteration 19, loss = 15744.49075587
Iteration 20, loss = 15528.66459945
Iteration 21, loss = 15282.63421802
Iteration 22, loss = 15108.00201303
Iteration 23, loss = 14852.13222606
Iteration 24, loss = 14451.16985574
Iteration 25, loss = 14498.76200502
Iteration 26, loss = 14339.88903194
Iteration 27, loss = 14183.00962376
Iteration 28, loss = 14214.442013

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 14.0min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.858101  ...              1034.590597  0.858101
1  RandomForestRegressor       0.999734  ...                44.755215  0.999734
2    KNeighborsRegressor       0.983253  ...               355.419488  0.983253
3           MLPRegressor       0.998934  ...                89.670842  0.998934

[4 rows x 7 columns]

# Sem Outliers Sem Normalização sem unamed

In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds = df_diamonds.drop(df_diamonds.columns[[0]], axis=1)

df_diamonds[df_diamonds.duplicated()].info()

df_number_type = df_diamonds.select_dtypes(exclude='O').columns[1:]



def range_for_remove_outliers(attr):
    df_attr = df_diamonds[attr]
    q3 = df_attr.quantile(q=0.75)
    q1 = df_attr.quantile(q=0.25)

    IQR  = q3 - q1
    min_IQR = q1 - 1.5 * IQR
    max_IQR = q3 + 1.5 * IQR
    
    return (min_IQR,max_IQR)

def remove_outlier(df_in, col_name):
    range_iqr = range_for_remove_outliers(col_name)
    df_out = df_in[~((df_in < range_iqr[0]) |(df_in > range_iqr[1])).any(axis=1)]
    return df_out


df_diamonds_ro = remove_outlier(df_diamonds.select_dtypes(exclude='O'),df_number_type)

y=df_diamonds_ro['price']
X=df_diamonds_ro.drop('price', axis=1)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.4, random_state=1)

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
# sc=StandardScaler()
# X_train_tx=sc.fit_transform(X_train)
# X_test_tx=sc.transform(X_test)


dataset_1 = (X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]

def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)

model_dict={'LinearRegression': LinearRegression(),
            'RandomForestRegressor': RandomForestRegressor(), 
            'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)
           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])
accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 1005 to 52861
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    146 non-null    float64
 1   cut      146 non-null    object 
 2   color    146 non-null    object 
 3   clarity  146 non-null    object 
 4   depth    146 non-null    float64
 5   table    146 non-null    float64
 6   price    146 non-null    int64  
 7   x        146 non-null    float64
 8   y        146 non-null    float64
 9   z        146 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 12.5+ KB

#### LinearRegression ####
score :0.8555
[0.85263266 0.86034477 0.85443187 0.85589875 0.85740044]

MSE    : 1115112.97 
MAE    : 660.71 
RMSE   : 1055.99 
R2     : 0.86 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   47.2s finished



#### RandomForestRegressor ####
score :0.8689
[0.86414463 0.86884806 0.86791363 0.86705533 0.86790236]

MSE    : 1011974.66 
MAE    : 601.92 
RMSE   : 1005.97 
R2     : 0.87 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.6s finished



#### KNeighborsRegressor ####
score :0.8597
[0.85231662 0.85246521 0.85680284 0.86094611 0.85813115]

MSE    : 1083059.11 
MAE    : 621.76 
RMSE   : 1040.70 
R2     : 0.86 
Iteration 1, loss = 924822.84811402
Iteration 2, loss = 562479.21913532
Iteration 3, loss = 555838.82349557
Iteration 4, loss = 557459.22773548
Iteration 5, loss = 550576.42717451
Iteration 6, loss = 546701.48786027
Iteration 7, loss = 545811.51224771
Iteration 8, loss = 541832.93667117
Iteration 9, loss = 538086.65839517
Iteration 10, loss = 535261.14489121
Iteration 11, loss = 530151.46726685
Iteration 12, loss = 532457.26531419
Iteration 13, loss = 531399.20087775
Iteration 14, loss = 528042.35274880
Iteration 15, loss = 528461.56361539
Iteration 16, loss = 529291.92862227
Iteration 17, loss = 527636.20033090
Iteration 18, loss = 526721.91295509
Iteration 19, loss = 524956.77875237
Iteration 20, loss = 523335.00132622
Iteration 21, loss = 524455.31163314
Iteration 22, loss = 524809.12057631
Iteration 23, loss = 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Iteration 1, loss = 1006478.00177991
Iteration 2, loss = 559588.40064691
Iteration 3, loss = 556293.25397300
Iteration 4, loss = 553089.08199570
Iteration 5, loss = 554832.75472966
Iteration 6, loss = 548770.49908664
Iteration 7, loss = 549478.13835990
Iteration 8, loss = 544633.78685809
Iteration 9, loss = 545171.52311899
Iteration 10, loss = 542449.79593755
Iteration 11, loss = 539374.48462403
Iteration 12, loss = 539076.19456427
Iteration 13, loss = 533019.34173466
Iteration 14, loss = 532261.05707915
Iteration 15, loss = 535948.60670531
Iteration 16, loss = 532731.66164499
Iteration 17, loss = 527949.07981652
Iteration 18, loss = 532505.38062221
Iteration 19, loss = 527820.46203109
Iteration 20, loss = 529793.14468824
Iteration 21, loss = 529323.73483505
Iteration 22, loss = 525849.96939304
Iteration 23, loss = 526462.42587001
Iteration 24, loss = 525922.25632462
Iteration 25, loss = 524917.36744201
Iteration 26, loss = 528818.86336741
Iteration 27, loss = 525600.03262663
Iteration

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 985918.31540956
Iteration 2, loss = 563624.14547787
Iteration 3, loss = 562734.15985587
Iteration 4, loss = 557067.75693980
Iteration 5, loss = 558513.19415250
Iteration 6, loss = 549283.16651416
Iteration 7, loss = 554077.92708083
Iteration 8, loss = 548595.94329484
Iteration 9, loss = 542878.59112043
Iteration 10, loss = 538827.12146689
Iteration 11, loss = 535929.31808605
Iteration 12, loss = 531408.83790545
Iteration 13, loss = 534475.51705996
Iteration 14, loss = 532633.63564140
Iteration 15, loss = 529192.65009116
Iteration 16, loss = 531227.41389810
Iteration 17, loss = 531123.15028342
Iteration 18, loss = 529018.22492818
Iteration 19, loss = 526992.77879199
Iteration 20, loss = 528345.31740216
Iteration 21, loss = 526418.61163819
Iteration 22, loss = 524286.45463710
Iteration 23, loss = 527299.84980261
Iteration 24, loss = 524068.21238887
Iteration 25, loss = 522882.94899455
Iteration 26, loss = 523805.23735603
Iteration 27, loss = 521371.85535694
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 996956.52331558
Iteration 2, loss = 562807.16210041
Iteration 3, loss = 554915.62297808
Iteration 4, loss = 556468.81810037
Iteration 5, loss = 554884.15376945
Iteration 6, loss = 548852.27745714
Iteration 7, loss = 548908.77295554
Iteration 8, loss = 545725.32149250
Iteration 9, loss = 543417.16822726
Iteration 10, loss = 537075.38597030
Iteration 11, loss = 535017.26333657
Iteration 12, loss = 534744.24718271
Iteration 13, loss = 529698.91912887
Iteration 14, loss = 527452.64242093
Iteration 15, loss = 526124.01150934
Iteration 16, loss = 528112.43838735
Iteration 17, loss = 528878.82284193
Iteration 18, loss = 525592.31753943
Iteration 19, loss = 527921.01855917
Iteration 20, loss = 523647.29609326
Iteration 21, loss = 522844.30223133
Iteration 22, loss = 524035.43022642
Iteration 23, loss = 521987.15199599
Iteration 24, loss = 523817.93996255
Iteration 25, loss = 520859.76677008
Iteration 26, loss = 520595.25769875
Iteration 27, loss = 520138.04718824
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 959210.06761259
Iteration 2, loss = 565473.36738487
Iteration 3, loss = 558537.25212065
Iteration 4, loss = 560448.58515387
Iteration 5, loss = 561214.90927597
Iteration 6, loss = 552280.03255197
Iteration 7, loss = 551869.89822819
Iteration 8, loss = 545916.69704352
Iteration 9, loss = 539476.37889713
Iteration 10, loss = 540838.67571633
Iteration 11, loss = 533755.76264074
Iteration 12, loss = 533718.92606315
Iteration 13, loss = 533830.67281589
Iteration 14, loss = 534320.65363116
Iteration 15, loss = 535058.80487362
Iteration 16, loss = 533703.62771727
Iteration 17, loss = 528231.49587568
Iteration 18, loss = 533207.29411041
Iteration 19, loss = 530067.35572612
Iteration 20, loss = 528579.20392322
Iteration 21, loss = 528529.12175113
Iteration 22, loss = 526643.61391459
Iteration 23, loss = 526087.33816815
Iteration 24, loss = 527302.74907156
Iteration 25, loss = 527514.50595280
Iteration 26, loss = 525410.61655198
Iteration 27, loss = 526505.31628896
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 987333.47261030
Iteration 2, loss = 567084.76266525
Iteration 3, loss = 566883.30718156
Iteration 4, loss = 560564.20889591
Iteration 5, loss = 560105.31456578
Iteration 6, loss = 557790.86296569
Iteration 7, loss = 555719.19542684
Iteration 8, loss = 556593.23674001
Iteration 9, loss = 549448.35592173
Iteration 10, loss = 547440.05149936
Iteration 11, loss = 543882.81723319
Iteration 12, loss = 542881.09511425
Iteration 13, loss = 540551.50340039
Iteration 14, loss = 538835.69055754
Iteration 15, loss = 539490.63043247
Iteration 16, loss = 536891.36424285
Iteration 17, loss = 534484.45858205
Iteration 18, loss = 537686.55835157
Iteration 19, loss = 534910.76922741
Iteration 20, loss = 535212.33930529
Iteration 21, loss = 534504.20046729
Iteration 22, loss = 533137.73813398
Iteration 23, loss = 535540.99371935
Iteration 24, loss = 529997.14963962
Iteration 25, loss = 528953.05587768
Iteration 26, loss = 530134.96591672
Iteration 27, loss = 531525.54840861
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 14.5min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.855497  ...              1055.989094  0.855497
1  RandomForestRegressor       0.868863  ...              1005.969513  0.868863
2    KNeighborsRegressor       0.859651  ...              1040.701258  0.859651
3           MLPRegressor       0.868463  ...              1007.499731  0.868463

[4 rows x 7 columns]

# Com outliers sem normalizacao com index

In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds[df_diamonds.duplicated()].info()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.4, random_state=1)

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)



dataset_1 = (X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]

def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)

model_dict={'LinearRegression': LinearRegression(), 
           'RandomForestRegressor': RandomForestRegressor(), 
            'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)


           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])
accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      int64  
 1   carat       0 non-null      float64
 2   cut         0 non-null      object 
 3   color       0 non-null      object 
 4   clarity     0 non-null      object 
 5   depth       0 non-null      float64
 6   table       0 non-null      float64
 7   price       0 non-null      int64  
 8   x           0 non-null      float64
 9   y           0 non-null      float64
 10  z           0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 0.0+ bytes

#### LinearRegression ####
score :0.8555
[0.85263266 0.86034477 0.85443187 0.85589875 0.85740044]

MSE    : 1115112.97 
MAE    : 660.71 
RMSE   : 1055.99 
R2     : 0.86 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   46.9s finished



#### RandomForestRegressor ####
score :0.8693
[0.86444634 0.86884417 0.869209   0.86747525 0.86729598]

MSE    : 1008884.88 
MAE    : 600.43 
RMSE   : 1004.43 
R2     : 0.87 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.4s finished



#### KNeighborsRegressor ####
score :0.8613
[0.85350391 0.85496279 0.85767089 0.86240715 0.86095406]

MSE    : 1070633.15 
MAE    : 617.38 
RMSE   : 1034.71 
R2     : 0.86 
Iteration 1, loss = 670123.57278805
Iteration 2, loss = 521968.47456195
Iteration 3, loss = 519286.75284513
Iteration 4, loss = 516950.13536633
Iteration 5, loss = 513324.85334913
Iteration 6, loss = 510576.53928142
Iteration 7, loss = 509678.10726395
Iteration 8, loss = 506284.43236135
Iteration 9, loss = 507010.10196432
Iteration 10, loss = 504286.16667736
Iteration 11, loss = 505188.83909339
Iteration 12, loss = 503830.09993460
Iteration 13, loss = 503377.88095890
Iteration 14, loss = 502138.37509172
Iteration 15, loss = 503356.15816265
Iteration 16, loss = 501197.24326674
Iteration 17, loss = 500113.19596566
Iteration 18, loss = 498699.97782468
Iteration 19, loss = 497207.78704763
Iteration 20, loss = 498913.76101323
Iteration 21, loss = 497157.17736510
Iteration 22, loss = 498281.15723463
Iteration 23, loss = 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Iteration 1, loss = 724473.15549483
Iteration 2, loss = 516867.69095560
Iteration 3, loss = 514346.59580421
Iteration 4, loss = 512135.36642159
Iteration 5, loss = 510312.87386635
Iteration 6, loss = 510151.50163853
Iteration 7, loss = 509389.49524690
Iteration 8, loss = 505950.94254909
Iteration 9, loss = 505507.76634452
Iteration 10, loss = 503565.99447618
Iteration 11, loss = 503215.28660926
Iteration 12, loss = 501239.00400759
Iteration 13, loss = 501443.42251041
Iteration 14, loss = 500053.37381869
Iteration 15, loss = 499350.55558056
Iteration 16, loss = 497971.13047819
Iteration 17, loss = 498603.65819228
Iteration 18, loss = 497508.99164835
Iteration 19, loss = 497487.34559824
Iteration 20, loss = 497146.66101066
Iteration 21, loss = 496166.26960134
Iteration 22, loss = 494654.02054020
Iteration 23, loss = 495251.65704670
Iteration 24, loss = 495785.18315498
Iteration 25, loss = 495159.23893078
Iteration 26, loss = 493036.82323336
Iteration 27, loss = 493709.74425739
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 702650.56975747
Iteration 2, loss = 517631.41981552
Iteration 3, loss = 513158.53055361
Iteration 4, loss = 510859.81462263
Iteration 5, loss = 509973.85759519
Iteration 6, loss = 508418.93897741
Iteration 7, loss = 507639.29236063
Iteration 8, loss = 506681.64804751
Iteration 9, loss = 506452.35891525
Iteration 10, loss = 504197.37659635
Iteration 11, loss = 503962.53368987
Iteration 12, loss = 503315.98612989
Iteration 13, loss = 500810.59641040
Iteration 14, loss = 501667.42829479
Iteration 15, loss = 501156.44267293
Iteration 16, loss = 501289.06149527
Iteration 17, loss = 500717.03617488
Iteration 18, loss = 498414.36794762
Iteration 19, loss = 497156.53140250
Iteration 20, loss = 498489.22405380
Iteration 21, loss = 497483.19660785
Iteration 22, loss = 497167.15006550
Iteration 23, loss = 495929.46898808
Iteration 24, loss = 495859.56335627
Iteration 25, loss = 493611.08705118
Iteration 26, loss = 494215.52164902
Iteration 27, loss = 492570.76456826
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 708535.22398022
Iteration 2, loss = 516161.87814125
Iteration 3, loss = 513486.30447058
Iteration 4, loss = 511062.83902876
Iteration 5, loss = 509027.50753108
Iteration 6, loss = 506520.01255614
Iteration 7, loss = 505108.90907864
Iteration 8, loss = 504067.77291884
Iteration 9, loss = 504748.87940178
Iteration 10, loss = 503007.14795233
Iteration 11, loss = 503421.74231409
Iteration 12, loss = 501597.87593082
Iteration 13, loss = 500072.40240974
Iteration 14, loss = 501200.94383126
Iteration 15, loss = 501546.09267131
Iteration 16, loss = 499451.93867082
Iteration 17, loss = 499178.59723109
Iteration 18, loss = 499004.11883552
Iteration 19, loss = 498397.72832046
Iteration 20, loss = 497155.73169534
Iteration 21, loss = 499061.58630036
Iteration 22, loss = 497922.27913238
Iteration 23, loss = 498103.40558834
Iteration 24, loss = 498096.52345837
Iteration 25, loss = 496802.02860724
Iteration 26, loss = 496250.31567727
Iteration 27, loss = 496844.91579804
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 715519.42027171
Iteration 2, loss = 519263.60713830
Iteration 3, loss = 516685.65101149
Iteration 4, loss = 513066.71537568
Iteration 5, loss = 511769.98321736
Iteration 6, loss = 508914.93414239
Iteration 7, loss = 508894.02137533
Iteration 8, loss = 508098.24627085
Iteration 9, loss = 507105.00302842
Iteration 10, loss = 505479.79595781
Iteration 11, loss = 505845.75026194
Iteration 12, loss = 504480.57850116
Iteration 13, loss = 504608.54997202
Iteration 14, loss = 502301.53836215
Iteration 15, loss = 502245.52193936
Iteration 16, loss = 502268.50428972
Iteration 17, loss = 502066.22103071
Iteration 18, loss = 501023.19432969
Iteration 19, loss = 500055.49524862
Iteration 20, loss = 500281.40233748
Iteration 21, loss = 500015.78295753
Iteration 22, loss = 498968.79375720
Iteration 23, loss = 498442.90224462
Iteration 24, loss = 498726.10405273
Iteration 25, loss = 497905.08513492
Iteration 26, loss = 498212.43528216
Iteration 27, loss = 500089.64376635
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 718726.91545018
Iteration 2, loss = 523874.92735195
Iteration 3, loss = 522739.12487347
Iteration 4, loss = 517914.31765188
Iteration 5, loss = 516960.58971386
Iteration 6, loss = 515935.26773350
Iteration 7, loss = 513239.21275214
Iteration 8, loss = 512570.18646103
Iteration 9, loss = 509971.67212859
Iteration 10, loss = 509170.44253139
Iteration 11, loss = 510035.27905517
Iteration 12, loss = 508972.34228566
Iteration 13, loss = 507514.53712739
Iteration 14, loss = 506315.74172438
Iteration 15, loss = 506491.03555646
Iteration 16, loss = 506206.02740251
Iteration 17, loss = 505896.22905015
Iteration 18, loss = 506442.53055592
Iteration 19, loss = 504602.98583631
Iteration 20, loss = 503169.00706609
Iteration 21, loss = 503350.52335823
Iteration 22, loss = 502926.60081210
Iteration 23, loss = 502854.42011508
Iteration 24, loss = 502033.82622071
Iteration 25, loss = 502245.78230022
Iteration 26, loss = 499484.02522695
Iteration 27, loss = 501121.88281409
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 14.0min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.855497  ...              1055.989094  0.855497
1  RandomForestRegressor       0.869263  ...              1004.432616  0.869263
2    KNeighborsRegressor       0.861261  ...              1034.714041  0.861261
3           MLPRegressor       0.871070  ...               997.468148  0.871070

[4 rows x 7 columns]


# Sem Outliers com normalizacao sem index

In [ ]:
import numpy as np
import pandas as pd# Aprendizado de Comitês
import matplotlib.pyplot as plt
import sklearn

df_diamonds = pd.read_csv('datasets/diamonds.csv')
df_diamonds[df_diamonds.duplicated()].info()

df_number_type = df_diamonds.select_dtypes(exclude='O').columns[1:]
df_diamonds = df_diamonds.drop(df_diamonds.columns[[0]], axis=1)



def range_for_remove_outliers(attr):
    df_attr = df_diamonds[attr]
    q3 = df_attr.quantile(q=0.75)
    q1 = df_attr.quantile(q=0.25)

    IQR  = q3 - q1
    min_IQR = q1 - 1.5 * IQR
    max_IQR = q3 + 1.5 * IQR
    
    return (min_IQR,max_IQR)

def remove_outlier(df_in, col_name):
    range_iqr = range_for_remove_outliers(col_name)
    df_out = df_in[~((df_in < range_iqr[0]) |(df_in > range_iqr[1])).any(axis=1)]
    return df_out


df_diamonds = remove_outlier(df_diamonds, df_number_type) 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.4, random_state=1)

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

dataset_1 = (X_train, X_test, y_train, y_test, 'dataset_1')

# Blank lists for all the details
model_=[]
cv_score_test=[]
cv_score_train=[]
mse_=[]
mae_=[]
rmse_=[]
r2_=[]

def run_model(model, dataset, modelname):
    model.fit(dataset[0], dataset[2])
    accuracies=cross_val_score(estimator=model, X=dataset[0], y=dataset[2], cv=5, verbose=1)
    y_pred=model.predict(dataset[1])
    print('')
    score_1=model.score(dataset[1], dataset[3])
    print(f'#### {modelname} ####')
    print("score :%.4f" %score_1)
    print(accuracies)
    
    
    mse=mean_squared_error(dataset[3], y_pred)
    mae=mean_absolute_error(dataset[3], y_pred)
    rmse=mean_squared_error(dataset[3], y_pred)**0.5
    r2=r2_score(dataset[3], y_pred)
   
    
    print('')
    print('MSE    : %0.2f ' % mse)
    print('MAE    : %0.2f ' % mae)
    print('RMSE   : %0.2f ' % rmse)
    print('R2     : %0.2f ' % r2)
    
    ## appending to the lists
    
    model_.append(modelname)
    cv_score_test.append(score_1)
    cv_score_train.append(np.mean(accuracies))
    mse_.append(mse)
    mae_.append(mae)
    rmse_.append(rmse)
    r2_.append(r2)

model_dict={'LinearRegression': LinearRegression(), 
            'RandomForestRegressor': RandomForestRegressor(), 
            'KNeighborsRegressor': KNeighborsRegressor(),
            'MLPRegressor': MLPRegressor(hidden_layer_sizes=(100,), batch_size=2, learning_rate_init=0.01, learning_rate="adaptive", max_iter=50, verbose=True)


           }

for models in model_dict:
    run_model(model_dict[models], dataset_1, models)

accuracy_data=pd.DataFrame(zip(model_, cv_score_test, cv_score_train, mse_, mae_, rmse_, r2_), columns=['Model', 'CV Test score', 'CV Train score (mean)', '%%SVGean Squared error', 'Mean Absolute error', 'Root Mean Squared error', 'R2 Score'])
accuracy_data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  0 non-null      int64  
 1   carat       0 non-null      float64
 2   cut         0 non-null      object 
 3   color       0 non-null      object 
 4   clarity     0 non-null      object 
 5   depth       0 non-null      float64
 6   table       0 non-null      float64
 7   price       0 non-null      int64  
 8   x           0 non-null      float64
 9   y           0 non-null      float64
 10  z           0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 0.0+ bytes


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished



#### LinearRegression ####
score :0.8555
[0.85263266 0.86034477 0.85443187 0.85589875 0.85740044]

MSE    : 1115112.97 
MAE    : 660.71 
RMSE   : 1055.99 
R2     : 0.86 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   46.8s finished



#### RandomForestRegressor ####
score :0.8686
[0.86544667 0.86808335 0.86831515 0.86731006 0.86702119]

MSE    : 1013805.92 
MAE    : 602.81 
RMSE   : 1006.88 
R2     : 0.87 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.4s finished



#### KNeighborsRegressor ####
score :0.8613
[0.85350391 0.85496279 0.85767089 0.86240715 0.86095406]

MSE    : 1070633.15 
MAE    : 617.38 
RMSE   : 1034.71 
R2     : 0.86 
Iteration 1, loss = 666585.33623783
Iteration 2, loss = 519373.55499862
Iteration 3, loss = 517383.82777375
Iteration 4, loss = 513308.66748300
Iteration 5, loss = 511496.59034624
Iteration 6, loss = 509941.67107923
Iteration 7, loss = 507121.47645375
Iteration 8, loss = 507248.43528854
Iteration 9, loss = 505895.12569100
Iteration 10, loss = 505215.57834367
Iteration 11, loss = 504649.39381326
Iteration 12, loss = 503713.90034564
Iteration 13, loss = 502427.45958943
Iteration 14, loss = 501123.09606855
Iteration 15, loss = 499188.69450853
Iteration 16, loss = 498622.82659672
Iteration 17, loss = 498521.00101287
Iteration 18, loss = 497734.15921653
Iteration 19, loss = 497343.90949426
Iteration 20, loss = 495050.79781315
Iteration 21, loss = 494113.35259859
Iteration 22, loss = 494880.63544982
Iteration 23, loss = 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Iteration 1, loss = 717868.28738532
Iteration 2, loss = 517044.21686080
Iteration 3, loss = 514475.54121946
Iteration 4, loss = 511309.29313772
Iteration 5, loss = 511323.37535723
Iteration 6, loss = 509198.11949090
Iteration 7, loss = 508691.21759355
Iteration 8, loss = 507504.71824568
Iteration 9, loss = 507749.48757419
Iteration 10, loss = 506179.76303132
Iteration 11, loss = 506045.87639353
Iteration 12, loss = 505068.28480854
Iteration 13, loss = 504653.07946942
Iteration 14, loss = 504002.87358900
Iteration 15, loss = 504151.45169696
Iteration 16, loss = 502719.06194855
Iteration 17, loss = 502440.25244034
Iteration 18, loss = 502669.81793176
Iteration 19, loss = 503017.24083248
Iteration 20, loss = 501124.80587032
Iteration 21, loss = 499935.71979047
Iteration 22, loss = 500778.97996266
Iteration 23, loss = 498079.38262680
Iteration 24, loss = 498296.16368857
Iteration 25, loss = 496446.62568560
Iteration 26, loss = 496040.99137761
Iteration 27, loss = 496119.55363629
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 708825.94489371
Iteration 2, loss = 519976.07562395
Iteration 3, loss = 518483.91864690
Iteration 4, loss = 513105.74891213
Iteration 5, loss = 513445.12499222
Iteration 6, loss = 511125.25593115
Iteration 7, loss = 508471.74000788
Iteration 8, loss = 507318.95534016
Iteration 9, loss = 504895.10330514
Iteration 10, loss = 506429.06839888
Iteration 11, loss = 505617.32110057
Iteration 12, loss = 504343.86445714
Iteration 13, loss = 502830.92654269
Iteration 14, loss = 501676.69082943
Iteration 15, loss = 502197.30943127
Iteration 16, loss = 499659.12848724
Iteration 17, loss = 501836.72966079
Iteration 18, loss = 499820.51009240
Iteration 19, loss = 500315.25154888
Iteration 20, loss = 498666.03924820
Iteration 21, loss = 498502.83715768
Iteration 22, loss = 498596.13768824
Iteration 23, loss = 499290.78498232
Iteration 24, loss = 497965.65082718
Iteration 25, loss = 498773.65410628
Iteration 26, loss = 497285.58604657
Iteration 27, loss = 496636.61000341
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 725535.99598354
Iteration 2, loss = 516336.40725559
Iteration 3, loss = 511906.77497371
Iteration 4, loss = 510169.55820234
Iteration 5, loss = 508630.32734013
Iteration 6, loss = 506952.99594205
Iteration 7, loss = 505327.49123731
Iteration 8, loss = 504656.22329911
Iteration 9, loss = 504451.27951633
Iteration 10, loss = 501715.45984677
Iteration 11, loss = 501996.93693130
Iteration 12, loss = 500647.93154506
Iteration 13, loss = 499912.24076349
Iteration 14, loss = 501193.28836083
Iteration 15, loss = 500033.59516565
Iteration 16, loss = 498717.52040998
Iteration 17, loss = 498800.45122394
Iteration 18, loss = 497441.74894309
Iteration 19, loss = 497555.80550396
Iteration 20, loss = 498149.20239259
Iteration 21, loss = 497161.58692128
Iteration 22, loss = 495912.03383013
Iteration 23, loss = 495623.91687271
Iteration 24, loss = 495250.56512722
Iteration 25, loss = 494898.27037126
Iteration 26, loss = 494978.87691393
Iteration 27, loss = 495831.07006358
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 706641.30618653
Iteration 2, loss = 517655.83267962
Iteration 3, loss = 515075.32663597
Iteration 4, loss = 511184.43754861
Iteration 5, loss = 510307.72840318
Iteration 6, loss = 508204.97803664
Iteration 7, loss = 507572.64935372
Iteration 8, loss = 505268.20584342
Iteration 9, loss = 505901.63495409
Iteration 10, loss = 503507.90800688
Iteration 11, loss = 502593.83704049
Iteration 12, loss = 502403.54137216
Iteration 13, loss = 502407.13146661
Iteration 14, loss = 500982.78387652
Iteration 15, loss = 501804.14986804
Iteration 16, loss = 500334.01380459
Iteration 17, loss = 498219.05943926
Iteration 18, loss = 499243.01301747
Iteration 19, loss = 498314.40681804
Iteration 20, loss = 499060.15936613
Iteration 21, loss = 498072.32581519
Iteration 22, loss = 499001.55429448
Iteration 23, loss = 497782.41668657
Iteration 24, loss = 498670.32730362
Iteration 25, loss = 496434.51210361
Iteration 26, loss = 497064.31318465
Iteration 27, loss = 496766.32093746
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 1, loss = 708979.86924119
Iteration 2, loss = 523753.87403829
Iteration 3, loss = 518004.24854207
Iteration 4, loss = 516289.80827216
Iteration 5, loss = 514427.25670101
Iteration 6, loss = 512767.41769652
Iteration 7, loss = 512112.06289844
Iteration 8, loss = 511080.18489626
Iteration 9, loss = 510947.29863089
Iteration 10, loss = 510760.38109316
Iteration 11, loss = 507947.87817147
Iteration 12, loss = 508870.35918202
Iteration 13, loss = 508303.92852710
Iteration 14, loss = 506316.11023693
Iteration 15, loss = 507036.08415427
Iteration 16, loss = 506299.00118955
Iteration 17, loss = 505510.76969252
Iteration 18, loss = 504891.82188392
Iteration 19, loss = 504332.44024344
Iteration 20, loss = 502767.27892224
Iteration 21, loss = 502121.23240865
Iteration 22, loss = 503301.30518165
Iteration 23, loss = 502797.28715388
Iteration 24, loss = 501540.66579415
Iteration 25, loss = 502851.41009083
Iteration 26, loss = 501816.55567434
Iteration 27, loss = 500707.76852324
Iteration 

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 14.2min finished


Model  CV Test score  ...  Root Mean Squared error  R2 Score
0       LinearRegression       0.855497  ...              1055.989094  0.855497
1  RandomForestRegressor       0.868625  ...              1006.879296  0.868625
2    KNeighborsRegressor       0.861261  ...              1034.714041  0.861261
3           MLPRegressor       0.872090  ...               993.513589  0.872090

[4 rows x 7 columns]